version: '3'

services:
  mysql:
    restart: always
    image: sameersbn/mysql:5.7.24
    environment:
    - DB_USER=${MYSQL_USER}
    - DB_PASS=${MYSQL_PASSWORD}
    - DB_NAME=${MYSQL_DB}
    volumes:
    - ${MYSQL_VOLUME:-mysql-volume}:/var/lib/mysql:Z

  akaunting:
    restart: always
    image: sameersbn/akaunting:1.3.9
    depends_on:
    - mysql
    command: app:akaunting
    environment:
    - DEBUG=false
    - TZ=${APPTZ}
    - DB_HOST=mysql
    - DB_USER=${MYSQL_USER}
    - DB_PASS=${MYSQL_PASSWORD}
    - DB_NAME=${MYSQL_DB}
    - AKAUNTING_URL=${AKAUNTING_URL}
    - AKAUNTING_COMPANY_NAME=${AKAUNTING_COMPANY_NAME}
    - AKAUNTING_COMPANY_EMAIL=${AKAUNTING_COMPANY_EMAIL}
    - AKAUNTING_ADMIN_EMAIL=${AKAUNTING_ADMIN_EMAIL}
    - AKAUNTING_ADMIN_PASSWORD=${AKAUNTING_ADMIN_PASSWORD}
    - AKAUNTING_BACKUPS_EXPIRY=0
    volumes:
    - ${AKAUNTING_VOLUME:-akaunting-volume}:/var/lib/akaunting

  nginx:
    restart: always
    image: sameersbn/akaunting:1.3.9
    command: app:nginx
    environment:
    - AKAUNTING_PHP_FPM_HOST=akaunting
    - AKAUNTING_PHP_FPM_PORT=9000
    depends_on:
    - akaunting
    ports:
    - "3000:80"

volumes:
  mysql-volume:
  akaunting-volume:

